version: '{build}'
clone_folder: c:\projects\cidssh
image:
    - Visual Studio 2019
configuration:
    - Release
platform:
    - x64
environment:
  matrix:
      - arch: Win32
matrix:
  fast_finish: true

# skip unsupported combinations
init:
    - echo %APPVEYOR_BUILD_WORKER_IMAGE%
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2019" ( set generator="Visual Studio 16 2019" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015" )
    - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2013" ( set generator="Visual Studio 12 2013" )
    - echo %generator%

build: off

test_script:
    - cmd: |-
        echo. >> c:\tools\vcpkg\triplets\x86-windows-static.cmake
        echo set(VCPKG_BUILD_TYPE release) >> c:\tools\vcpkg\triplets\x86-windows-static.cmake
        vcpkg install --triplet x86-windows-static openssl boost-beast boost-asio boost-system
        git submodule update --init --recursive
        cmake --version
        cmake -S . -B build -G %generator% -A %arch% -DVCPKG_TARGET_TRIPLET="x86-windows-static" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake
        cmake --build build --config %CONFIGURATION%
