FROM alpine:latest
RUN apk add --no-cache build-base cmake autoconf libtool pkgconf git mercurial file linux-headers wget
COPY . /Cid-SSH/
WORKDIR /Cid-SSH/

RUN rm -rf build && mkdir build

# Building openssl statically (Requirement for libssh)
RUN cd build && wget https://www.openssl.org/source/openssl-1.1.0j.tar.gz && tar xf openssl-1.1.0j.tar.gz
RUN cd build/openssl-1.1.0j && ./config -fPIC && make && make install

# Building libssh statically (Requirement for CidSSH) 
RUN cd build && wget https://www.libssh.org/files/0.8/libssh-0.8.7.tar.xz && tar xf libssh-0.8.7.tar.xz
# Patch to remove __FILE__ reference
RUN cd build/libssh-0.8.7 && sed -i -e 's/__FILE__/"misc.c"/' src/misc.c
RUN cd build/libssh-0.8.7 && mkdir build && cd build && cmake -DWITH_GSSAPI=OFF -DWITH_ZLIB=OFF -DWITH_SFTP=OFF -DWITH_STATIC_LIB=ON -DWITH_PCAP=OFF -DWITH_NACL=OFF -DCMAKE_BUILD_TYPE=Release .. && make && make install

# Building CidSSH
RUN cd build && cmake -DLIBSSH_LIBRARY=/usr/local/lib/libssh.a -DLIBSSH_INCLUDE=libssh-0.8.7/include/ -DLIBSSH_CONFIG_FOLDER=libssh-0.8.7/build/ -DCMAKE_BUILD_TYPE=Release .. && make 