version: 2.1
jobs:
    build:
        docker:
            - image: alpine:latest
        steps:
            - checkout
            - run:
                name: Install some necessary dependencies
                command: |
                    apk add --no-cache build-base cmake autoconf libtool pkgconf git mercurial file linux-headers wget libc-dev
            - run:
                name: Pull submodules
                command:
                    git submodule update --init --recursive
            - run:
                name: Download and install OpenSSL
                command: |
                    cd /tmp
                    wget https://www.openssl.org/source/openssl-1.1.0j.tar.gz && tar xf openssl-1.1.0j.tar.gz
                    cd openssl-1.1.0j && ./config -fPIC && make && make install
            - run:
                name: Build our software
                command: |
                    mkdir build
                    cd build
                    cmake ..
                    make
