version: 2.1
jobs:
    build:
        docker:
            - image: alpine:edge
        steps:
            - checkout
            - run:
                name: Install some necessary dependencies
                command: |
                    apk add --no-cache build-base cmake autoconf libtool pkgconf git mercurial file linux-headers wget libc-dev
            - run:
                name: Pull submodules
                command:
                    git submodule update --init --recursive
            - run:
                name: Build CidSSH
                command: |
                    sh ./build.sh
