name: Build for macOS
on: [push]

jobs:
    build:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Install OpenSSL/Boost from Homebrew
              run: |
                  brew install openssl pkg-config cmake boost git cmake
                  brew info openssl
            - name: Install vcpkg and libssh
              run: |
                  git clone https://github.com/Microsoft/vcpkg.git
                  cd vcpkg
                  ./bootstrap-vcpkg.sh                  
                  VCPKG_FORCE_SYSTEM_BINARIES=1 VCPKG_BUILD_TYPE=release ./vcpkg install libssh[core,openssl] --triplet x64-osx
            - name: Create build directory
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --version
                  cmake -S . -B build
            - name: Build CidSSH in Release mode
              run: |
                  export LDFLAGS="-L/usr/local/opt/openssl/lib"
                  export CPPFLAGS="-I/usr/local/opt/openssl/include"
                  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"
                  cmake --build build --config release -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH-macos
                  path: build/src/malware/CidSSH

