name: Build for Windows
on: [push]

jobs:
    build:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Install OpenSSL from vcpkg
              run: |
                  vcpkg install openssl
            - name: Create build directory
              run: |
                  cmake --version
                  cmake -S . -B build -G "Visual Studio 16 2019" -A Win32 -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake
            - name: Build CidSSH in Release mode
              run: |
                  cmake --build build --config Release
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH.exe
                  path: build/src/malware/Release/CidSSH.exe

