name: Build for Windows
on: [push]

jobs:
    build:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Update vcpkg triplet to only build release
              run: |
                  echo.  >> %VCPKG_INSTALLATION_ROOT%\triplets\x86-windows-static.cmake
                  echo set(VCPKG_BUILD_TYPE release) >> %VCPKG_INSTALLATION_ROOT%\triplets\x86-windows-static.cmake
            - name: Install OpenSSL/Boost from vcpkg
              run: |
                  vcpkg install --triplet x86-windows-static openssl boost
            - name: Create build directory
              run: |
                  cmake --version
                  cmake -S . -B build -G "Visual Studio 16 2019" -A Win32 -DVCPKG_TARGET_TRIPLET="x86-windows-static" -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake
            - name: Build CidSSH in Release mode
              run: |
                  cmake --build build --config Release
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH.exe
                  path: build/src/malware/Release/CidSSH.exe

