name: Build for Windows
on: [push]

jobs:
    build:
        runs-on: windows-2019
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Update vcpkg triplet to only build release
              run: |
                  "`r`nset(VCPKG_BUILD_TYPE release)" | Add-Content "$env:VCPKG_INSTALLATION_ROOT\triplets\x64-windows-static.cmake"
            - name: Install OpenSSL/Boost from vcpkg
              run: |
                  $env:VCPKG_INSTALLATION_ROOT\bootstrap-vcpkg.bat
                  vcpkg version
                  vcpkg install --triplet x64-windows-static boost-beast boost-asio boost-system libssh[core,openssl]
            - name: Create ssh version
              run: |
                  cmake -S . -B build -DWITH_WEBSOCKETS=OFF -G "Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET="x64-windows-static" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
            - name: Build CidSSH in Release mode
              run: |
                  cmake --build build --config Release
            - name: Create ws version
              run: |
                  cmake -S . -B build_ws -DWITH_WEBSOCKETS=ON -G "Visual Studio 16 2019" -A x64 -DVCPKG_TARGET_TRIPLET="x64-windows-static" -DCMAKE_TOOLCHAIN_FILE="$env:VCPKG_INSTALLATION_ROOT\scripts\buildsystems\vcpkg.cmake" -DCMAKE_BUILD_TYPE=Release
            - name: Build CidSSH in Release mode
              run: |
                  cmake --build build_ws --config Release
                  
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_win_ssh_x64.exe
                  path: build/src/malware/Release/CidSSH.exe                 
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_win_ws_x64.exe
                  path: build_ws/src/malware/Release/CidSSH.exe

