name: Build for Linux
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Build CidSSH
              uses: docker://alpine:edge
              with: 
                  args: sh ./build.sh
