name: Build the software on Push
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Build the OpenSSL/Software
              uses: docker://alpine:latest
              with: 
                  args: sh ./build.sh
