name: Build for Linux
on: [push]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v1
              with:
                  submodules: true
            - name: Build CidSSH
              uses: docker://alpine:edge
              with: 
                  args: sh ./build.sh
                  
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_lnx_ssh_x64
                  path: build/src/malware/CidSSH                 
            - uses: actions/upload-artifact@master
              with:
                  name: CidSSH_lnx_ws_x64
                  path: build_ws/src/malware/CidSSH
